package xmlparser

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"
)

func TestParseIVR(t *testing.T) {
	s, err := NewIVRScript(strings.NewReader(xmlData))
	if err != nil {
		panic(err)
	}
	exp, err := json.MarshalIndent(s, "", "  ")
	fmt.Println(string(exp))
	if err == nil {
		t.Error("\nIvrxml: marshalling error", err)
	}
	// more sanity checking...

}

var xmlData = `<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<ivrScript>
    <domainId>115675</domainId>
    <properties/>
    <modules>
        <incomingCall>
            <singleDescendant>E966C8048939446B8680C6DC86B603FD</singleDescendant>
            <moduleName>IncomingCall12</moduleName>
            <locationX>87</locationX>
            <locationY>132</locationY>
            <moduleId>2060AC8FEE174A5ABAE086D36CA4A98C</moduleId>
            <data/>
        </incomingCall>
        <query>
            <ascendants>E966C8048939446B8680C6DC86B603FD</ascendants>
            <exceptionalDescendant>A56CB456D56A4F44B06009CD833CE4E5</exceptionalDescendant>
            <singleDescendant>4E8C591A3E5A495DBFE688E80850A5DF</singleDescendant>
            <moduleName>Query24</moduleName>
            <locationX>301</locationX>
            <locationY>132</locationY>
            <moduleId>3889A8058A794604863B3AE44BB88BE1</moduleId>
            <data>
                <prompt>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </prompt>
                <vivrPrompts>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrPrompts>
                <vivrHeader>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrHeader>
                <textChannelData>
                    <textPrompts>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </textPrompts>
                    <isUsedVivrPrompts>true</isUsedVivrPrompts>
                    <isTextOnly>true</isTextOnly>
                </textChannelData>
                <url>https://api.five9.com/wsadmin/v11/AdminWebService</url>
                <method>POST</method>
                <fetchTimeout>5</fetchTimeout>
                <parameters/>
                <returnValues>
                    <entry>
                        <key>__BUFFER__</key>
                        <value>__BUFFER__</value>
                    </entry>
                </returnValues>
                <storeNumberOfArrayElementsInVariable>false</storeNumberOfArrayElementsInVariable>
                <requestInfo>
                    <template>
                        <base64>H4sIAAAAAAAAAG2RTW7DIBBG9zkF8gGYdS3KIlGlrHOBCsHnBBUzFhCa3L71n9KkXgHvzegbQGU2
A2JtP2JF4AHi1oeY2wW/N5dShpYo2wt6k+WvHZXkdKZxQ1j6qFk7kR5dSNVbSON6H+V3lp2veJOW
e2r0Tgih1vgjjEOiZ7hnd5/IBJHaM8qBYzG2nGA5uayFWPxUE5i/rsMh+YLkjf6jRmu3+ag6j+B0
NgG542Tx6Z2iGf4vriZcoRXN60sIbaUo2p5M0fatdrN7eobHef0q/QNhcqWBvQEAAA==</base64>
                    </template>
                    <replacements>
                        <position>314</position>
                        <variableName>sergei.qwerty</variableName>
                    </replacements>
                </requestInfo>
                <headers>
                    <entry>
                        <key>Content-Type</key>
                        <value>
                            <isVarSelected>false</isVarSelected>
                            <stringValue>
                                <value>text/xml; charset=utf-8</value>
                                <id>0</id>
                            </stringValue>
                        </value>
                    </entry>
                </headers>
                <requestBodyType>XML_JSON</requestBodyType>
                <authProfileHolder>
                    <extrnalObj>
                        <id>31</id>
                        <name>SystemAccount</name>
                    </extrnalObj>
                    <varSelected>false</varSelected>
                </authProfileHolder>
                <responseInfos>
                    <from>200</from>
                    <to>200</to>
                    <method>REG_EXP</method>
                    <regexp>
                        <regexp>&lt;data(&gt;[^/&gt;]*|/&gt;)(&lt;/data&gt;)?&lt;data(&gt;[^/&gt;]*|/&gt;)(&lt;/data&gt;)?&lt;data(&gt;[^/&gt;]*|/&gt;)(&lt;/data&gt;)?&lt;/values&gt;</regexp>
                        <regexpParameters>
                            <groupIndex>0</groupIndex>
                            <variable>__BUFFER__</variable>
                        </regexpParameters>
                        <regexpParameters>
                            <groupIndex>1</groupIndex>
                        </regexpParameters>
                        <regexpParameters>
                            <groupIndex>2</groupIndex>
                        </regexpParameters>
                        <regexpParameters>
                            <groupIndex>3</groupIndex>
                        </regexpParameters>
                        <regexpParameters>
                            <groupIndex>4</groupIndex>
                        </regexpParameters>
                        <regexpParameters>
                            <groupIndex>5</groupIndex>
                        </regexpParameters>
                        <regexpFlags>0</regexpFlags>
                    </regexp>
                </responseInfos>
                <responseInfos>
                    <from>200</from>
                    <to>500</to>
                    <method>REG_EXP</method>
                    <regexp>
                        <regexp>(.+)</regexp>
                        <regexpParameters>
                            <groupIndex>0</groupIndex>
                            <variable>__BUFFER__</variable>
                        </regexpParameters>
                        <regexpFlags>0</regexpFlags>
                    </regexp>
                </responseInfos>
                <saveStatusCode>false</saveStatusCode>
                <saveReasonPhrase>false</saveReasonPhrase>
            </data>
        </query>
        <input>
            <ascendants>2060AC8FEE174A5ABAE086D36CA4A98C</ascendants>
            <singleDescendant>3889A8058A794604863B3AE44BB88BE1</singleDescendant>
            <moduleName>Input22</moduleName>
            <locationX>199</locationX>
            <locationY>132</locationY>
            <moduleId>E966C8048939446B8680C6DC86B603FD</moduleId>
            <data>
                <dispo>
                    <id>-17</id>
                    <name>Caller Disconnected</name>
                </dispo>
                <vivrPrompts>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrPrompts>
                <vivrHeader>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrHeader>
                <textChannelData>
                    <textPrompts>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </textPrompts>
                    <isUsedVivrPrompts>true</isUsedVivrPrompts>
                    <isTextOnly>true</isTextOnly>
                </textChannelData>
                <grammar xsi:type="digits" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                    <mainReturnValue>
                        <name>MEANING</name>
                        <type>STRING</type>
                        <varName>sergei.qwerty</varName>
                    </mainReturnValue>
                    <stringProperty>
                        <type>LANGUAGE</type>
                        <value xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema">en-US</value>
                        <enabled>true</enabled>
                    </stringProperty>
                    <intProperty>
                        <type>MINLENGTH</type>
                        <value xsi:type="xs:int" xmlns:xs="http://www.w3.org/2001/XMLSchema">1</value>
                        <enabled>true</enabled>
                    </intProperty>
                    <intProperty>
                        <type>MAXLENGTH</type>
                        <value xsi:type="xs:int" xmlns:xs="http://www.w3.org/2001/XMLSchema">20</value>
                        <enabled>true</enabled>
                    </intProperty>
                    <additionalReturnValues>
                        <name>SWI_literal</name>
                        <type>STRING</type>
                    </additionalReturnValues>
                    <propertiesToVariables/>
                </grammar>
                <prompts>
                    <prompt>
                        <ttsPrompt>
                            <xml>H4sIAAAAAAAAAIVRwU7DMAy97yus3LfADaG01SZAmgQnGHePWlO11EG1O5a/py1SWVomcnLee3rv
yXbFufZwokaqwJm5Xd0YIP4IZcWHzOzenpZ3BkSRS/SBKTORxBT5wskn4fHRU02s+QK651C1qfat
kvwAA+iRD+uO+IUGmLGmvIu+73lnh2+qGN3e0be0QSE49VNmiJe7V2MvQmya4uy0iquU6stagnEt
Sf15sNgJMzEZcaWz/un1v2fqfY3chzLmz6TQSn+MRlfwghG2cOTwBTG0DWwfCmcH3byfvVrQ2eli
7Hwzo6gjk6t/AxQ50EE9AgAA</xml>
                            <promptTTSEnumed>false</promptTTSEnumed>
                        </ttsPrompt>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </prompt>
                    <count>1</count>
                </prompts>
                <recoEvents>
                    <event>NO_MATCH</event>
                    <count>1</count>
                    <compoundPrompt>
                        <multiLanguagesPromptItem>
                            <prompt>2DF2A8093D2949E498B91327C11D7BDE</prompt>
                        </multiLanguagesPromptItem>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </compoundPrompt>
                    <action>CONTINUE</action>
                </recoEvents>
                <recoEvents>
                    <event>NO_INPUT</event>
                    <count>1</count>
                    <compoundPrompt>
                        <multiLanguagesPromptItem>
                            <prompt>479F3DCC1D35493AA3A4E11E1A0FE70D</prompt>
                        </multiLanguagesPromptItem>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </compoundPrompt>
                    <action>REPROMPT</action>
                </recoEvents>
                <confirmData>
                    <confirmRequired>REQUIRED</confirmRequired>
                    <requiredConfidence>75</requiredConfidence>
                    <maxAttemptsToConfirm>3</maxAttemptsToConfirm>
                    <noInputTimeout>3</noInputTimeout>
                    <maxTimeToEnter>3</maxTimeToEnter>
                    <completeTimeout>0</completeTimeout>
                    <confidenceTreshold>75</confidenceTreshold>
                    <sensitivity>0</sensitivity>
                    <incompleteTimeout>0</incompleteTimeout>
                    <swirecNbestListLength>0</swirecNbestListLength>
                    <recognizeConfigParameters>
                        <recognizeConfigParameter>NO_INPUT_TIMEOUT</recognizeConfigParameter>
                        <recognizeConfigParameter>CONFIDENCE_TRESHOLD</recognizeConfigParameter>
                        <recognizeConfigParameter>MAX_TIME_TO_ENTER</recognizeConfigParameter>
                    </recognizeConfigParameters>
                    <prompt>
                        <multiLanguagesPromptItem>
                            <prompt>5E4010AB6DAC4DCAAA96835B9CD647F7</prompt>
                        </multiLanguagesPromptItem>
                        <interruptible>true</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </prompt>
                    <recoEvents>
                        <event>NO_MATCH</event>
                        <count>1</count>
                        <compoundPrompt>
                            <multiLanguagesPromptItem>
                                <prompt>2DF2A8093D2949E498B91327C11D7BDE</prompt>
                            </multiLanguagesPromptItem>
                            <interruptible>false</interruptible>
                            <canChangeInterruptableOption>true</canChangeInterruptableOption>
                            <ttsEnumed>false</ttsEnumed>
                            <exitModuleOnException>false</exitModuleOnException>
                        </compoundPrompt>
                        <action>REPROMPT</action>
                    </recoEvents>
                    <recoEvents>
                        <event>NO_INPUT</event>
                        <count>1</count>
                        <compoundPrompt>
                            <multiLanguagesPromptItem>
                                <prompt>479F3DCC1D35493AA3A4E11E1A0FE70D</prompt>
                            </multiLanguagesPromptItem>
                            <interruptible>false</interruptible>
                            <canChangeInterruptableOption>true</canChangeInterruptableOption>
                            <ttsEnumed>false</ttsEnumed>
                            <exitModuleOnException>false</exitModuleOnException>
                        </compoundPrompt>
                        <action>REPROMPT</action>
                    </recoEvents>
                </confirmData>
                <confidenceTreshold>5</confidenceTreshold>
                <maxTimeToEnter>15</maxTimeToEnter>
                <noInputTimeout>5</noInputTimeout>
                <sensitivity>50</sensitivity>
                <incompleteTimeout>2</incompleteTimeout>
                <completeTimeout>0</completeTimeout>
                <swirecNbestListLength>2</swirecNbestListLength>
                <maxAttempts>3</maxAttempts>
                <collapsible>false</collapsible>
                <recognizeConfigParameters>
                    <recognizeConfigParameter>NO_INPUT_TIMEOUT</recognizeConfigParameter>
                    <recognizeConfigParameter>CONFIDENCE_TRESHOLD</recognizeConfigParameter>
                    <recognizeConfigParameter>MAX_TIME_TO_ENTER</recognizeConfigParameter>
                </recognizeConfigParameters>
                <recordUserInput>false</recordUserInput>
                <dtmfHelpButton>null</dtmfHelpButton>
            </data>
        </input>
        <play>
            <ascendants>3889A8058A794604863B3AE44BB88BE1</ascendants>
            <ascendants>1CA3A5E090744A048B3F487DBCD68856</ascendants>
            <singleDescendant>696AA64AABE74B7A99D648EA4451D55F</singleDescendant>
            <moduleName>Play53</moduleName>
            <locationX>618</locationX>
            <locationY>240</locationY>
            <moduleId>A56CB456D56A4F44B06009CD833CE4E5</moduleId>
            <data>
                <prompt>
                    <ttsPrompt>
                        <xml>H4sIAAAAAAAAAIVSy07DMBC89ysWn2kMN4SclILgxkOiBfW4TZfUqmMHr1M1fD1OkEqTUuGTd2Y9
M9q1muxKA1vyrJ1NxWVyIYBs7lbaFqmYzx7GVwI4oF2hcZZS0RCLSTZSXBFu7g2VZEM2gngUhuD1
sg7EP0AHGrTFNBK/UAdbLCmL1tctr2RX9jv2am9oarpFJti2t1SQHc9fhTwwkX0XJYdRlA5UHsZi
bKbci39szHLADET2eKBd+FPrf82+9ily6VZN9k6AlTOu0F90DlEM0BhwH+BqD1hEcwb0BHntfSxM
A8isOcRNggtr8pAbHQnAAGGtGYIuKYGFqyFHC1SiNtC0Yp81xWfOQnDAdVU5H27unh9fpk+LJHdl
ArM12k3be6Zkl+14JvLkUJQcLkMeb2PfFMneT/sGbKxw7LECAAA=</xml>
                        <promptTTSEnumed>false</promptTTSEnumed>
                    </ttsPrompt>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </prompt>
                <dispo>
                    <id>-17</id>
                    <name>Caller Disconnected</name>
                </dispo>
                <vivrPrompts>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrPrompts>
                <vivrHeader>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrHeader>
                <textChannelData>
                    <textPrompts>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </textPrompts>
                    <isUsedVivrPrompts>true</isUsedVivrPrompts>
                    <isTextOnly>true</isTextOnly>
                </textChannelData>
                <numberOfDigits>0</numberOfDigits>
                <terminateDigit>N/A</terminateDigit>
                <clearDigitBuffer>false</clearDigitBuffer>
                <collapsible>false</collapsible>
            </data>
        </play>
        <hangup>
            <ascendants>A56CB456D56A4F44B06009CD833CE4E5</ascendants>
            <ascendants>F13B997B0CB1440492CC2DAE818529EA</ascendants>
            <ascendants>890C5CA7466B4F51AEBA46824456BA65</ascendants>
            <ascendants>03C8951EFC414905BD71E2922ACD12B2</ascendants>
            <moduleName>Hangup58</moduleName>
            <locationX>791</locationX>
            <locationY>131</locationY>
            <moduleId>696AA64AABE74B7A99D648EA4451D55F</moduleId>
            <data>
                <dispo>
                    <id>0</id>
                    <name>No Disposition</name>
                </dispo>
                <returnToCallingModule>true</returnToCallingModule>
                <errCode>
                    <isVarSelected>false</isVarSelected>
                    <integerValue>
                        <value>0</value>
                    </integerValue>
                </errCode>
                <errDescription>
                    <isVarSelected>false</isVarSelected>
                    <stringValue>
                        <value></value>
                        <id>0</id>
                    </stringValue>
                </errDescription>
                <overwriteDisposition>true</overwriteDisposition>
            </data>
        </hangup>
        <case>
            <ascendants>4E8C591A3E5A495DBFE688E80850A5DF</ascendants>
            <moduleName>Case2</moduleName>
            <locationX>494</locationX>
            <locationY>132</locationY>
            <moduleId>1CA3A5E090744A048B3F487DBCD68856</moduleId>
            <data>
                <branches>
                    <entry>
                        <key>golden</key>
                        <value>
                            <name>golden</name>
                            <desc>F13B997B0CB1440492CC2DAE818529EA</desc>
                            <conditions>
                                <comparisonType>EQUALS</comparisonType>
                                <rightOperand>
                                    <isVarSelected>false</isVarSelected>
                                    <stringValue>
                                        <value>&gt;GOLDEN</value>
                                        <id>0</id>
                                    </stringValue>
                                </rightOperand>
                                <leftOperand>
                                    <isVarSelected>true</isVarSelected>
                                    <variableName>__BUFFER__</variableName>
                                </leftOperand>
                            </conditions>
                        </value>
                    </entry>
                    <entry>
                        <key>silver</key>
                        <value>
                            <name>silver</name>
                            <desc>890C5CA7466B4F51AEBA46824456BA65</desc>
                            <conditions>
                                <comparisonType>EQUALS</comparisonType>
                                <rightOperand>
                                    <isVarSelected>false</isVarSelected>
                                    <stringValue>
                                        <value>&gt;SILVER</value>
                                        <id>0</id>
                                    </stringValue>
                                </rightOperand>
                                <leftOperand>
                                    <isVarSelected>true</isVarSelected>
                                    <variableName>__BUFFER__</variableName>
                                </leftOperand>
                            </conditions>
                        </value>
                    </entry>
                    <entry>
                        <key>bronze</key>
                        <value>
                            <name>bronze</name>
                            <desc>03C8951EFC414905BD71E2922ACD12B2</desc>
                            <conditions>
                                <comparisonType>EQUALS</comparisonType>
                                <rightOperand>
                                    <isVarSelected>false</isVarSelected>
                                    <stringValue>
                                        <value>&gt;BRONZE</value>
                                        <id>0</id>
                                    </stringValue>
                                </rightOperand>
                                <leftOperand>
                                    <isVarSelected>true</isVarSelected>
                                    <variableName>__BUFFER__</variableName>
                                </leftOperand>
                            </conditions>
                        </value>
                    </entry>
                    <entry>
                        <key>No Match</key>
                        <value>
                            <name>No Match</name>
                            <desc>A56CB456D56A4F44B06009CD833CE4E5</desc>
                            <conditions/>
                        </value>
                    </entry>
                </branches>
            </data>
        </case>
        <skillTransfer>
            <ascendants>1CA3A5E090744A048B3F487DBCD68856</ascendants>
            <singleDescendant>696AA64AABE74B7A99D648EA4451D55F</singleDescendant>
            <moduleName>GoldenSkills</moduleName>
            <locationX>627</locationX>
            <locationY>37</locationY>
            <moduleId>F13B997B0CB1440492CC2DAE818529EA</moduleId>
            <data>
                <dispo>
                    <id>-5</id>
                    <name>Abandon</name>
                </dispo>
                <maxQueueTime>600</maxQueueTime>
                <queueIfOnCall>true</queueIfOnCall>
                <onCallQueueTime>600</onCallQueueTime>
                <queueIfOnBreakOrLoggedOut>false</queueIfOnBreakOrLoggedOut>
                <onBreakOrLoggedOutQueueTime>600</onBreakOrLoggedOutQueueTime>
                <onQueueTimeoutExpiration>false</onQueueTimeoutExpiration>
                <pauseBeforeTransfer>0</pauseBeforeTransfer>
                <maxRingTime>15</maxRingTime>
                <placeOnBreakIfNoAnswer>true</placeOnBreakIfNoAnswer>
                <vmTransferOnQueueTimeout>false</vmTransferOnQueueTimeout>
                <vmTransferOnDigit>false</vmTransferOnDigit>
                <vmBoxType>SKILL</vmBoxType>
                <clearDigitBuffer>true</clearDigitBuffer>
                <enableMusicOnHold>true</enableMusicOnHold>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <priorityChangeType>INCREASE</priorityChangeType>
                <priorityChangeValue>
                    <isVarSelected>false</isVarSelected>
                    <integerValue>
                        <value>10</value>
                    </integerValue>
                </priorityChangeValue>
                <listOfSkillsEx>
                    <extrnalObj>
                        <id>266188</id>
                        <name>Premium Support</name>
                    </extrnalObj>
                    <varSelected>false</varSelected>
                </listOfSkillsEx>
                <taskType>0</taskType>
                <transferAlgorithm>
                    <algorithmType>LongestReadyTime</algorithmType>
                    <statAlgorithmTimeWindow>E15minutes</statAlgorithmTimeWindow>
                </transferAlgorithm>
                <recordedFilesAction>KEEP_AS_RECORDINGD</recordedFilesAction>
                <callbackNumberFromCav>
                    <id>63</id>
                    <name>number</name>
                </callbackNumberFromCav>
                <callbackPhoneNumberPrompt>
                    <id>-26</id>
                    <name>QC1YourPhoneNumberIs</name>
                </callbackPhoneNumberPrompt>
                <callbackConfirmingPhoneNumberPrompt>
                    <id>-27</id>
                    <name>QC2PressOneIfCorrect</name>
                </callbackConfirmingPhoneNumberPrompt>
                <callbackEnteringPhoneNumberPrompt>
                    <id>-28</id>
                    <name>QC3PleaseEnterYourPhoneNumber</name>
                </callbackEnteringPhoneNumberPrompt>
                <callbackRecordingCallerNamePrompt>
                    <id>-36</id>
                    <name>QC5PleaseClearlySayYourName</name>
                </callbackRecordingCallerNamePrompt>
                <callbackConfirmationPrompt>
                    <id>-29</id>
                    <name>QC4YouWillBeCalled</name>
                </callbackConfirmationPrompt>
                <callbackQueueTimeoutSec>18000</callbackQueueTimeoutSec>
                <callbackEnterDigitsMaxTimeSec>5</callbackEnterDigitsMaxTimeSec>
                <callbackAllowInternational>false</callbackAllowInternational>
                <isTcpaConsentEnabled>false</isTcpaConsentEnabled>
                <tcpaConsentText>H4sIAAAAAAAAADWOwQ3DMAwDV+EARYboL58uUPSh2EwjwJYCy878TVDkS/IOnJHcgtbRHY2JehBJ
SgmszSvezxFqjMBLKj+Qc7gRnYX75kbYqAsb9uaHZmbI4gcfUEtlZLXv1VTv6iblL55mDMts0cXy
aTuV9wcNmHfIFWS9IPiKfbS0SXD6AQLT2xmtAAAA</tcpaConsentText>
                <ignoreSkillsOrder>false</ignoreSkillsOrder>
                <recordCallerNameOnQueueCallback>false</recordCallerNameOnQueueCallback>
            </data>
        </skillTransfer>
        <skillTransfer>
            <ascendants>1CA3A5E090744A048B3F487DBCD68856</ascendants>
            <singleDescendant>696AA64AABE74B7A99D648EA4451D55F</singleDescendant>
            <moduleName>SilverSkill</moduleName>
            <locationX>684</locationX>
            <locationY>96</locationY>
            <moduleId>890C5CA7466B4F51AEBA46824456BA65</moduleId>
            <data>
                <dispo>
                    <id>-5</id>
                    <name>Abandon</name>
                </dispo>
                <maxQueueTime>600</maxQueueTime>
                <queueIfOnCall>true</queueIfOnCall>
                <onCallQueueTime>600</onCallQueueTime>
                <queueIfOnBreakOrLoggedOut>false</queueIfOnBreakOrLoggedOut>
                <onBreakOrLoggedOutQueueTime>600</onBreakOrLoggedOutQueueTime>
                <onQueueTimeoutExpiration>false</onQueueTimeoutExpiration>
                <pauseBeforeTransfer>0</pauseBeforeTransfer>
                <maxRingTime>15</maxRingTime>
                <placeOnBreakIfNoAnswer>true</placeOnBreakIfNoAnswer>
                <vmTransferOnQueueTimeout>false</vmTransferOnQueueTimeout>
                <vmTransferOnDigit>false</vmTransferOnDigit>
                <vmBoxType>SKILL</vmBoxType>
                <clearDigitBuffer>true</clearDigitBuffer>
                <enableMusicOnHold>true</enableMusicOnHold>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <announcements>
                    <enabled>false</enabled>
                    <loopped>false</loopped>
                    <timeout>1</timeout>
                    <prompt/>
                    <annType>EWT</annType>
                </announcements>
                <priorityChangeType>INCREASE</priorityChangeType>
                <priorityChangeValue>
                    <isVarSelected>false</isVarSelected>
                    <integerValue>
                        <value>10</value>
                    </integerValue>
                </priorityChangeValue>
                <listOfSkillsEx>
                    <extrnalObj>
                        <id>266194</id>
                        <name>sk_skill1</name>
                    </extrnalObj>
                    <varSelected>false</varSelected>
                </listOfSkillsEx>
                <taskType>0</taskType>
                <transferAlgorithm>
                    <algorithmType>LongestReadyTime</algorithmType>
                    <statAlgorithmTimeWindow>E15minutes</statAlgorithmTimeWindow>
                </transferAlgorithm>
                <recordedFilesAction>KEEP_AS_RECORDINGD</recordedFilesAction>
                <callbackNumberFromCav>
                    <id>63</id>
                    <name>number</name>
                </callbackNumberFromCav>
                <callbackPhoneNumberPrompt>
                    <id>-26</id>
                    <name>QC1YourPhoneNumberIs</name>
                </callbackPhoneNumberPrompt>
                <callbackConfirmingPhoneNumberPrompt>
                    <id>-27</id>
                    <name>QC2PressOneIfCorrect</name>
                </callbackConfirmingPhoneNumberPrompt>
                <callbackEnteringPhoneNumberPrompt>
                    <id>-28</id>
                    <name>QC3PleaseEnterYourPhoneNumber</name>
                </callbackEnteringPhoneNumberPrompt>
                <callbackRecordingCallerNamePrompt>
                    <id>-36</id>
                    <name>QC5PleaseClearlySayYourName</name>
                </callbackRecordingCallerNamePrompt>
                <callbackConfirmationPrompt>
                    <id>-29</id>
                    <name>QC4YouWillBeCalled</name>
                </callbackConfirmationPrompt>
                <callbackQueueTimeoutSec>18000</callbackQueueTimeoutSec>
                <callbackEnterDigitsMaxTimeSec>5</callbackEnterDigitsMaxTimeSec>
                <callbackAllowInternational>false</callbackAllowInternational>
                <isTcpaConsentEnabled>false</isTcpaConsentEnabled>
                <tcpaConsentText>H4sIAAAAAAAAADWOwQ3DMAwDV+EARYboL58uUPSh2EwjwJYCy878TVDkS/IOnJHcgtbRHY2JehBJ
SgmszSvezxFqjMBLKj+Qc7gRnYX75kbYqAsb9uaHZmbI4gcfUEtlZLXv1VTv6iblL55mDMts0cXy
aTuV9wcNmHfIFWS9IPiKfbS0SXD6AQLT2xmtAAAA</tcpaConsentText>
                <ignoreSkillsOrder>false</ignoreSkillsOrder>
                <recordCallerNameOnQueueCallback>false</recordCallerNameOnQueueCallback>
            </data>
        </skillTransfer>
        <skillTransfer>
            <ascendants>1CA3A5E090744A048B3F487DBCD68856</ascendants>
            <singleDescendant>696AA64AABE74B7A99D648EA4451D55F</singleDescendant>
            <moduleName>SkillTransfer4</moduleName>
            <locationX>685</locationX>
            <locationY>169</locationY>
            <moduleId>03C8951EFC414905BD71E2922ACD12B2</moduleId>
            <data>
                <dispo>
                    <id>-5</id>
                    <name>Abandon</name>
                </dispo>
                <maxQueueTime>600</maxQueueTime>
                <queueIfOnCall>true</queueIfOnCall>
                <onCallQueueTime>600</onCallQueueTime>
                <queueIfOnBreakOrLoggedOut>false</queueIfOnBreakOrLoggedOut>
                <onBreakOrLoggedOutQueueTime>600</onBreakOrLoggedOutQueueTime>
                <onQueueTimeoutExpiration>false</onQueueTimeoutExpiration>
                <pauseBeforeTransfer>0</pauseBeforeTransfer>
                <maxRingTime>15</maxRingTime>
                <placeOnBreakIfNoAnswer>true</placeOnBreakIfNoAnswer>
                <vmTransferOnQueueTimeout>false</vmTransferOnQueueTimeout>
                <vmTransferOnDigit>false</vmTransferOnDigit>
                <vmBoxType>SKILL</vmBoxType>
                <clearDigitBuffer>true</clearDigitBuffer>
                <enableMusicOnHold>true</enableMusicOnHold>
                <priorityChangeType>INCREASE</priorityChangeType>
                <priorityChangeValue>
                    <isVarSelected>false</isVarSelected>
                    <integerValue>
                        <value>10</value>
                    </integerValue>
                </priorityChangeValue>
                <taskType>0</taskType>
                <transferAlgorithm>
                    <algorithmType>LongestReadyTime</algorithmType>
                    <statAlgorithmTimeWindow>E15minutes</statAlgorithmTimeWindow>
                </transferAlgorithm>
                <recordedFilesAction>KEEP_AS_RECORDINGD</recordedFilesAction>
                <callbackPhoneNumberPrompt>
                    <id>-26</id>
                    <name>CallbackPhoneNumberPrompt</name>
                </callbackPhoneNumberPrompt>
                <callbackConfirmingPhoneNumberPrompt>
                    <id>-27</id>
                    <name>CallbackConfirmingPhoneNumberPrompt</name>
                </callbackConfirmingPhoneNumberPrompt>
                <callbackEnteringPhoneNumberPrompt>
                    <id>-28</id>
                    <name>CallbackEnteringPhoneNumberPrompt</name>
                </callbackEnteringPhoneNumberPrompt>
                <callbackRecordingCallerNamePrompt>
                    <id>-36</id>
                    <name>CallbackRecordingCallerNamePrompt</name>
                </callbackRecordingCallerNamePrompt>
                <callbackConfirmationPrompt>
                    <id>-29</id>
                    <name>CallbackConfirmationPrompt</name>
                </callbackConfirmationPrompt>
                <callbackQueueTimeoutSec>18000</callbackQueueTimeoutSec>
                <callbackEnterDigitsMaxTimeSec>5</callbackEnterDigitsMaxTimeSec>
                <callbackAllowInternational>false</callbackAllowInternational>
                <isTcpaConsentEnabled>false</isTcpaConsentEnabled>
                <tcpaConsentText>H4sIAAAAAAAAADWOwQ3DMAwDV+EARYboL58uUPSh2EwjwJYCy878TVDkS/IOnJHcgtbRHY2JehBJ
SgmszSvezxFqjMBLKj+Qc7gRnYX75kbYqAsb9uaHZmbI4gcfUEtlZLXv1VTv6iblL55mDMts0cXy
aTuV9wcNmHfIFWS9IPiKfbS0SXD6AQLT2xmtAAAA</tcpaConsentText>
                <ignoreSkillsOrder>false</ignoreSkillsOrder>
                <recordCallerNameOnQueueCallback>false</recordCallerNameOnQueueCallback>
            </data>
        </skillTransfer>
        <play>
            <ascendants>3889A8058A794604863B3AE44BB88BE1</ascendants>
            <singleDescendant>1CA3A5E090744A048B3F487DBCD68856</singleDescendant>
            <moduleName>info</moduleName>
            <locationX>397</locationX>
            <locationY>132</locationY>
            <moduleId>4E8C591A3E5A495DBFE688E80850A5DF</moduleId>
            <data>
                <prompt>
                    <ttsPrompt>
                        <xml>H4sIAAAAAAAAAO1UwU6EMBC971d0e3at3symsNk1Szx5UDHxRAaYkMbSmraQ5e8FTJDCEi8e3MSe
pu81b968TMp3p1KSGo0VWgX09vqGElSZzoUqAhq/RJs7SqwDlYPUCgPaoKW7cMXtB8L7UWKJyoUr
0h4OzhmRVg7tF9CDElSxb4lvqIcVlBi2rbcdz1l/9V8Maq8gKzyARVJ3VUBRbeJnykZNmN+Fs6kV
LhyWY1sWmr317M8bWzZhJiID7vDkzmr9rOlrL5GpzpvwAZurdrS+nntgiyY4mw7Pzk/PazACUomX
lctvROKN/9gtY5Ic4ig6PiUJZx4xinExr0tcrzW516ow4CoJrv0M7Jq86cqQzGAuHLGZNkiE3f6v
4Dy7P7aCg3Ybs/dNfwLtwpa27gUAAA==</xml>
                        <promptTTSEnumed>false</promptTTSEnumed>
                    </ttsPrompt>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </prompt>
                <dispo>
                    <id>-17</id>
                    <name>Caller Disconnected</name>
                </dispo>
                <vivrPrompts>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrPrompts>
                <vivrHeader>
                    <interruptible>false</interruptible>
                    <canChangeInterruptableOption>true</canChangeInterruptableOption>
                    <ttsEnumed>false</ttsEnumed>
                    <exitModuleOnException>false</exitModuleOnException>
                </vivrHeader>
                <textChannelData>
                    <textPrompts>
                        <interruptible>false</interruptible>
                        <canChangeInterruptableOption>true</canChangeInterruptableOption>
                        <ttsEnumed>false</ttsEnumed>
                        <exitModuleOnException>false</exitModuleOnException>
                    </textPrompts>
                    <isUsedVivrPrompts>true</isUsedVivrPrompts>
                    <isTextOnly>true</isTextOnly>
                </textChannelData>
                <numberOfDigits>0</numberOfDigits>
                <terminateDigit>N/A</terminateDigit>
                <clearDigitBuffer>false</clearDigitBuffer>
                <collapsible>false</collapsible>
            </data>
        </play>
    </modules>
    <modulesOnHangup>
        <startOnHangup>
            <singleDescendant>88411529FF324EA0BA41B82A98F1873D</singleDescendant>
            <moduleName>StartOnHangup12</moduleName>
            <locationX>20</locationX>
            <locationY>10</locationY>
            <moduleId>48BB70AF2C0D4FFD8EF3334FF34F9213</moduleId>
        </startOnHangup>
        <hangup>
            <ascendants>48BB70AF2C0D4FFD8EF3334FF34F9213</ascendants>
            <moduleName>Hangup16</moduleName>
            <locationX>120</locationX>
            <locationY>10</locationY>
            <moduleId>88411529FF324EA0BA41B82A98F1873D</moduleId>
            <data>
                <dispo>
                    <id>-17</id>
                    <name>Caller Disconnected</name>
                </dispo>
                <returnToCallingModule>true</returnToCallingModule>
                <errCode>
                    <isVarSelected>false</isVarSelected>
                    <integerValue>
                        <value>0</value>
                    </integerValue>
                </errCode>
                <errDescription>
                    <isVarSelected>false</isVarSelected>
                    <stringValue>
                        <value></value>
                        <id>0</id>
                    </stringValue>
                </errDescription>
                <overwriteDisposition>false</overwriteDisposition>
            </data>
        </hangup>
    </modulesOnHangup>
    <userVariables>
        <entry>
            <key>fname</key>
            <value>
                <name>fname</name>
                <description></description>
                <stringValue>
                    <value></value>
                    <id>0</id>
                </stringValue>
                <attributes>8</attributes>
                <isNullValue>true</isNullValue>
            </value>
        </entry>
        <entry>
            <key>lname</key>
            <value>
                <name>lname</name>
                <description></description>
                <stringValue>
                    <value></value>
                    <id>0</id>
                </stringValue>
                <attributes>8</attributes>
                <isNullValue>true</isNullValue>
            </value>
        </entry>
    </userVariables>
    <multiLanguagesPrompts>
        <entry>
            <key>2DF2A8093D2949E498B91327C11D7BDE</key>
            <value>
                <promptId>2DF2A8093D2949E498B91327C11D7BDE</promptId>
                <name>NoMatchPrompt</name>
                <description>Default prompt for NoMatch event</description>
                <type>AUDIO</type>
                <prompts>
                    <entry key="en-US">
                        <ttsPrompt>
                            <xml>H4sIAAAAAAAAAIWRQYvCMBCF7/6KkLvO7k0krSis4Fnd+2gHCZtOpTMV++83VqimXdmcku+F9x4z
bnkrg7lSLb7izH7OPqwhPlWF53NmD/vNdG6NKHKBoWLKbEtil/nEyYXw5ytQSaz5xMTjULX2x0ZJ
HqCDAfm8isITdZixpDxGL+66g+6Z/ujdvjE0tEYhc73fMks8PewsvIRAmuJgWMV5pfK1lmC7kqT+
OFhgoAxMeq500z+9/vdMvd+Jx6po821cS13TSY3nS6MzBx0e14G3fRwM5wDjQfSfopgs+RfRtLpi
LAIAAA==</xml>
                            <promptTTSEnumed>false</promptTTSEnumed>
                        </ttsPrompt>
                    </entry>
                </prompts>
                <defaultLanguage>en-US</defaultLanguage>
                <isPersistent>true</isPersistent>
            </value>
        </entry>
        <entry>
            <key>479F3DCC1D35493AA3A4E11E1A0FE70D</key>
            <value>
                <promptId>479F3DCC1D35493AA3A4E11E1A0FE70D</promptId>
                <name>NoInputPrompt</name>
                <description>Default prompt for NoInput event</description>
                <type>AUDIO</type>
                <prompts>
                    <entry key="en-US">
                        <ttsPrompt>
                            <xml>H4sIAAAAAAAAAIWRQYvCMBCF7/6KkHsdvS1LWnFhBc+7eh/toMV0Ip2p2H9vrVBNu7I5Je8b3ntM
3OJaenOhSorAqZ1PZ9YQ70Ne8CG1m99V8mGNKHKOPjCltiGxi2zi5Ex4+vZUEms2Me1xqFoVu1pJ
HkIneuTDsgVPqZMZS8ra6M87d9A944nebYu+pi8UMpf7LbXEyebHwksIxCkOhlVcoVS+1hJslhLV
HwcLDMjApNeVrvqn1/+esfc7uAt5k63NHpmDmiNhZZpQTx10YFwI3jZyMNwEjFfRD7Uw+uYbQw31
uC4CAAA=</xml>
                            <promptTTSEnumed>false</promptTTSEnumed>
                        </ttsPrompt>
                    </entry>
                </prompts>
                <defaultLanguage>en-US</defaultLanguage>
                <isPersistent>true</isPersistent>
            </value>
        </entry>
        <entry>
            <key>5E4010AB6DAC4DCAAA96835B9CD647F7</key>
            <value>
                <promptId>5E4010AB6DAC4DCAAA96835B9CD647F7</promptId>
                <name>ConfirmPrompt</name>
                <description>Default prompt for user input confirmation</description>
                <type>AUDIO</type>
                <prompts>
                    <entry key="en-US">
                        <ttsPrompt>
                            <xml>H4sIAAAAAAAAANVTUWvCMBB+91ccebeZexqSVhw4EMTB1A2fSrQ3DWsTyaXO/vulHXNttQwGe1jI
Q/J9ue++3CVidMpSOKIlZXTIBsENA9Rbkyi9C9lq+dC/Y0BO6kSmRmPICiQ2inqCDijfJilmqF3U
Az+EdM6qTe6QPoEKTKXejT3xDVWwlhlGPvWw5AWvts0TZ7VnmeZ4LwnhWK5Chrq/WjBeS8KbWQRv
WxHKYVa3RbIYU8P+ZWLiLaYlcsYdntxVrZ81m9pd5MYkRbQ2uW+NQ4vJ0F+xwi698E4zgreLwK9X
QRylVXKT4q/q0wa/xOZli+N48TKNZ9Pl5Gk8i2PBG2zNWaeF/9i5ABayALb2XweMhYNFImADBuoV
3F4R+Lk11uLWBfDo9mjflX/uVAbNTT3mlv1V48+HPNn42h9LoLssIgQAAA==</xml>
                            <promptTTSEnumed>false</promptTTSEnumed>
                        </ttsPrompt>
                    </entry>
                </prompts>
                <defaultLanguage>en-US</defaultLanguage>
                <isPersistent>true</isPersistent>
            </value>
        </entry>
        <entry>
            <key>9DB914BECE5741A7814C72B920E94EBC</key>
            <value>
                <promptId>9DB914BECE5741A7814C72B920E94EBC</promptId>
                <name>ConfirmPromptWithoutVSR</name>
                <description>Default prompt for user input confirmation with disabled voice recognition</description>
                <type>AUDIO</type>
                <prompts>
                    <entry key="en-US">
                        <ttsPrompt>
                            <xml>H4sIAAAAAAAAANVT0UrDMBR931eEvK9xPslIOypMGAwVtyk+lbS9bsE0GUla17837bA23YYg+GDJ
Q3PO5ZyTexM6OxQCVaANVzLEk+AKI5CZyrnchnizvhvfYGQskzkTSkKIazB4Fo2o2QN7nwsoQNpo
hNxHmbWap6UFcwRaUDC5jR3xDbWwZAVEznra8JS0W7+iU3tmooRbZgBVzV+IQY43K0x6JsR3oWQY
hXILRT+WYXVsvPinxoYMmIFIh1s42LNaP2v62pfIVOV19KpKNxoLGvKpO2KLnWYhF8NQMmwCOd8F
WjHNWSrgV/0Zgl9i982Ik2T1skiWi/X8KV4mCSUe20t2McJ/nFyAHjUYg/AEI/6G7I4b5FamtIbM
BujB7kB/cHfD98e6a/xX8+2KHOm94E/oteYzCQQAAA==</xml>
                            <promptTTSEnumed>false</promptTTSEnumed>
                        </ttsPrompt>
                    </entry>
                </prompts>
                <defaultLanguage>en-US</defaultLanguage>
                <isPersistent>true</isPersistent>
            </value>
        </entry>
    </multiLanguagesPrompts>
    <multiLanguagesVIVRPrompts/>
    <multiLanguagesTextPrompts/>
    <multiLanguagesMenuChoices/>
    <multiLanguagesEwtAnnouncement/>
    <languages/>
    <functions/>
    <defaultLanguage>en-US</defaultLanguage>
    <defaultMethod>GET</defaultMethod>
    <defaultFetchTimeout>5</defaultFetchTimeout>
    <showLabelNames>true</showLabelNames>
    <defaultVivrTimeout>5</defaultVivrTimeout>
    <unicodeEncoding>false</unicodeEncoding>
    <useShortcut>false</useShortcut>
    <resetErrorCode>true</resetErrorCode>
    <showAllChannelPrompts>false</showAllChannelPrompts>
    <extContactFieldsInput>true</extContactFieldsInput>
    <extContactFieldsOutput>true</extContactFieldsOutput>
    <timeoutInMilliseconds>3600000</timeoutInMilliseconds>
    <version>1100008</version>
</ivrScript>`
