package common

/*For Third Party Transfer*/
const CHECK_INTERNATIONAL = true

/*For Case and If-Else*/
const MAX_BRANCH_NAME_SIZE = 35

const MIN_BRANCH_NAME_SIZE = 10

const CURR_BRANCH_NAME_SIZE = MIN_BRANCH_NAME_SIZE

const NUMBER_OF_BRANCHES = 100

const MAX_IF_ELSE_DIGITS = 255

/*For Play and Get Digits Module*/
const DEFAULT_MAX_DIGITS = 4

const MIN_NUMBER_DIGITS = 0

const MAX_NUMBER_DIGITS = 25

const DEFAULT_TERMINATION_DIGIT = "#"

//const DEFAULT_MAX_SILENCE  = 5
//const DEFAULT_MAX_TIME  = 30
const DEFAULT_MAX_SILENCE = 2

const DEFAULT_MAX_TIME = 20

const DEFAULT_TONE_MAX_TIME = 8

const DEFAULT_TONE_MIN_TIME = 5

/* For Skill Transfer (all time values are in seconds) */
const MAX_QUEUE_TIME = 59*60 + 59 // maximum supported by format mm:ss

const SKILL_TRANSFER_MAX_QUEUE_TIME = 999*60 + 99

const MIN_QUEUE_TIME = 1

const DEFAULT_SKILL_TRANSFER_QUEUE_TIME = 10 * 60

const DEFAULT_AGENT_TRANSFER_QUEUE_TIME = 60

const DEFAULT_SKILL_TRANSFER_BUSY_UNAVAILABLE_QUEUE_TIME = 10 * 60

const ONE_HOUR_QUEUE_TIME = 60 * 60

const MAX_SKILL_TRANSFER_PAUSE_BEFORE_TRANSFER = 10

const MAX_AGENT_TRANSFER_PAUSE_BEFORE_TRANSFER = 20

const MIN_PAUSE_BEFORE_TRANSFER = 0

const MAX_RING_TIME = 60

const MIN_RING_TIME = 2

const DEFAULT_RING_TIME = 15

const DEFAULT_RING_TIME_IN_TCPA_MODE = 30

const MAX_PRIORITY = 100

const MIN_PRIORITY = 0

const ANNOUNCEMENTS_NUMBER = 5

const MIN_ANNOUNCEMENT_TIMEOUT = 0

const MAX_ANNOUNCEMENT_TIMEOUT = 3600

const DEFAULT_ANNOUNCEMENT_TIMEOUT = 1

const IVR_SCRIPT = 0

const BRANCH = 1

const AGENT_TRANSFER = 1

// IVR value flags
const IVR_SCRIPT_NEEDS_VERSION_UPDATE = 0

// Queue Callback constants

const MIN_CALLBACK_QUEUE_TIMEOUT_SEC = 30

const MAX_CALLBACK_QUEUE_TIMEOUT_SEC = 10 * 24 * 60 * 60 // 10 days

const DEFAULT_CALLBACK_QUEUE_TIMEOUT_SEC = 5 * 60 * 60 // 5 hours

const MIN_CALLBACK_ENTER_DIGITS_MAX_TIME_SEC = 5

const MAX_CALLBACK_ENTER_DIGITS_MAX_TIME_SEC = 60

const DEF_CALLBACK_ENTER_DIGITS_MAX_TIME_SEC = MIN_CALLBACK_ENTER_DIGITS_MAX_TIME_SEC
